//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by AntiVirus.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_ANTIVIRUS_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDR_VIRDATA                     131
#define IDC_STATIC_SCANNING_DATA        1000
#define IDC_STATIC_PATH                 1001
#define IDC_EDIT_PATH                   1002
#define IDC_BUTTON_BROWSE               1003
#define IDC_STATIC_SCAN_DATA            1004
#define IDC_STATIC_INFE_DATA            1005
#define IDC_STATIC_REPA_DATA            1006
#define IDC_STATIC_NOT_REPA_DATA        1007
#define IDC_STATIC_REPORT               1008
#define IDC_BUTTON_SCAN                 1009
#define IDC_LIST_REPORT                 1010
#define IDC_BUTTON_ABOUT                1014
#define IDC_STATIC_SC                   1017
#define IDC_STATIC_IN                   1018
#define IDC_STATIC_RE                   1019
#define IDC_STATIC_NO                   1020
#define IDC_STATIC_DELE                 1021
#define IDC_STATIC_DELE_DATA            1022

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1023
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
